FROM superarch/minarch

RUN pacman --overwrite "*" -Sy --noconfirm --nodeps elixir coreutils sed base

RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment

RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen

RUN echo "LANG=en_US.UTF-8" > /etc/locale.conf

RUN locale-gen en_US.UTF-8

RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8

RUN export LC_ALL=en_US.UTF-8

ENV LC_ALL en_US.UTF-8 
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  

WORKDIR /app

COPY run.sh /app

CMD ["bash", "run.sh"]
